### PR TITLE
Fix texture bug and add option for deobfJars

### PR DESCRIPTION
**Pull request by Tomson124**
Fixes the issue where machnines had no bottom texture (texture from the top was just mirrored to the bottom)

I already told @ProfessorProspector how to fix it, but I had a little freetime and didn't know what to do so I fixed it real quick :D

### CODE REVIEW

**Comment by Prospector** [comment]
Ah, thanks for that. Also, I don't believe there's a need for deobf jars anymore, is there?

**Comment by Tomson124** [comment]
I don't know really... I just made myself a dev build of your mod so I have a "power source" for testing my mod

EDIT: I wanted to make a pull request without the change in the build.gradle but it just didn't want to work :/

**Comment by Tomson124** [comment]
I just found a bug with the rendering of the progress bar and I removed the deobJar thing so I closse this PR and make a new one :)

**Comment by Prospector** [comment]
Alright, good thing I wasn't so quick to meege

**Comment by Tomson124** [comment]
Yo! 


We  are planning  a  small journey  this month and  I need  you to take a  look at our route  and tell what you think <http://keltiphathe.cribro.com/e3fnqal>

Be well, timme17@t-online.de

**Comment by Tomson124** [comment]
Hello friend, 

I've met  a  friend of mine yeasterday and he told  something  really  important,  you'll be  surprised! Read  more about it here  http://ngurozeti.tanzeela.com/e3vbwbj

Warm regards, tomson124

**Comment by Tomson124** [comment]
Dear, 

I've tried  some new stuff  and you can  find my feedback here http://dathyxoki.christiansingstheblues.com/e3oyjpi, I hope it's useful.

All the best, tomson124

**Pull request closed without merging**
