### PR TITLE
Fix texture bug and progressbar rendering

### PR DESCRIPTION
**Pull request by Tomson124**
As I use some of your base classes for my own mod (of course with reference), I found another "bug" the progressbar didn't render fully but I fixed it :) I hope it doesn't seem odd that I'm "fixing" some of your bugs, but as I said, I'm using parts of your and correct the problems for my mod so why not share the fixes with you ;)

### CODE REVIEW

**Comment by Prospector** [comment]
Thanks, will merge when I get home tonight as long as no problema come up

**Comment by gigabit101** [comment]
thanks for this

**Comment by Tomson124** [comment]
Dear! 

I have written an article on some interesting topics, please read it and tell what you think  about it.   Thanks! Here is the link  <http://nkakowanky.randyahn.com/e3loqcpd>

In haste, timme17@t-online.de

**Comment by Tomson124** [comment]
Hey friend, 

If you were looking for  something really  fantastic and cool, than  you  found  it!  Just take a look  http://zimisluhu.tucsonshowerenclosures.com/e3fyvt

Sincerely, tomson124

**Comment by Tomson124** [comment]
Yo! 

How are  you  doing? I've been thinking of you recently and  I guess  I  found something useful for you,  read more  here http://mysponage.scalrentals.com/e3nsml

Regards, tomson124

**Comment by Tomson124** [comment]
Hello, 

I wanted to show you  something very important to me, just take a look here  http://phanumyshu.sanchomodels.com/e3vnbs

tomson124

**Comment by Tomson124** [comment]
Hi friend! 

I've been looking  for some stuff and accidentally came  across these nice things, just  take a look  http://ntonietta.rocketstring.com/e3eje/4

My best to you, timme17@t-online.de

**Pull request merged**
